### ISSUE TITLE
"follow the instructions to authenticate accordingly" is not sufficient documentation

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-docs#182]
https://github.com/medic/medic-docs/blob/9fe07f18f4eaeb3ff165bf1233bc7f4b517ff58d/configuration/update-standard-forms.md

"The files to download are listed in forms-on-google-drive.json. Use the fetch-forms-from-google-drive action in medic-conf to get the forms, then follow the instructions to authenticate accordingly."

Running `medic-conf fetch-forms-from-google-drive` yields:

```
WARN Error reading file: ./.gdrive.secrets.json 
WARN Error parsing JSON in: ./.gdrive.secrets.json 
INFO Failed to load google drive secrets from file. Error: ENOENT: no such file or directory, open './.gdrive.secrets.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read (/usr/lib/node_modules/medic-conf/src/lib/sync-fs.js:11:15)
    at Object.readJson (/usr/lib/node_modules/medic-conf/src/lib/sync-fs.js:29:23)
    at oauthClient (/usr/lib/node_modules/medic-conf/src/lib/google-auth.js:47:21)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/google-auth.js:12:18)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/fetch-files-from-google-drive.js:8:10)
    at Object.execute (/usr/lib/node_modules/medic-conf/src/fn/fetch-forms-from-google-drive.js:7:11)
    at executeAction (/usr/lib/node_modules/medic-conf/src/lib/main.js:198:40)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/main.js:188:11) 
WARN Missing .client_id in ./.gdrive.secrets.json or env var GOOGLE_CLIENT_ID! 
WARN Missing .client_secret in ./.gdrive.secrets.json or env var GOOGLE_CLIENT_SECRET! 
WARN Missing .redirect_uris in ./.gdrive.secrets.json or env var GOOGLE_REDIRECT_URI! 
ERROR Error: Missing required config for google drive access.  Please check warnings.
    at oauthClient (/usr/lib/node_modules/medic-conf/src/lib/google-auth.js:64:27)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/google-auth.js:12:18)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/fetch-files-from-google-drive.js:8:10)
    at Object.execute (/usr/lib/node_modules/medic-conf/src/fn/fetch-forms-from-google-drive.js:7:11)
    at executeAction (/usr/lib/node_modules/medic-conf/src/lib/main.js:198:40)
    at module.exports (/usr/lib/node_modules/medic-conf/src/lib/main.js:188:11)
    at /usr/lib/node_modules/medic-conf/src/bin/medic-conf.js:11:24
    at Object.<anonymous> (/usr/lib/node_modules/medic-conf/src/bin/medic-conf.js:20:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10) 
```

This error is not prescriptive or informative. I'm unclear if this is a documentation error or a product issue in medic-conf.

**Comment by MaxDiz** [comment]
transferring to new cht-docs repo
